//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.NuGetExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.NuGetExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packageDetails &apos;{0}&apos; depends on API &apos;{1}&apos; min version &apos;{2}&apos; but the installed version is &apos;{3}&apos;.
        /// </summary>
        internal static string NuGetExplorer_ApiPackageRegistry_Validation_Error_Message_Pattern_1 {
            get {
                return ResourceManager.GetString("NuGetExplorer_ApiPackageRegistry_Validation_Error_Message_Pattern_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packageDetails &apos;{0}&apos; depends on API &apos;{1}&apos; min version greater than &apos;{2}&apos; but the installed version is &apos;{3}&apos;.
        /// </summary>
        internal static string NuGetExplorer_ApiPackageRegistry_Validation_Error_Message_Pattern_2 {
            get {
                return ResourceManager.GetString("NuGetExplorer_ApiPackageRegistry_Validation_Error_Message_Pattern_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packageDetails &apos;{0}&apos; depends on API &apos;{1}&apos; max version &apos;{2}&apos; but the installed version is &apos;{3}&apos;.
        /// </summary>
        internal static string NuGetExplorer_ApiPackageRegistry_Validation_Error_Message_Pattern_3 {
            get {
                return ResourceManager.GetString("NuGetExplorer_ApiPackageRegistry_Validation_Error_Message_Pattern_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packageDetails &apos;{0}&apos; depends on API &apos;{1}&apos; max version lower than &apos;{2}&apos; but the installed version is &apos;{3}&apos;.
        /// </summary>
        internal static string NuGetExplorer_ApiPackageRegistry_Validation_Error_Message_Pattern_4 {
            get {
                return ResourceManager.GetString("NuGetExplorer_ApiPackageRegistry_Validation_Error_Message_Pattern_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include prerelease.
        /// </summary>
        internal static string NuGetExplorer_ExplorerWindow_CheckBox_Content_IncludePrerelease {
            get {
                return ResourceManager.GetString("NuGetExplorer_ExplorerWindow_CheckBox_Content_IncludePrerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended updates.
        /// </summary>
        internal static string NuGetExplorer_ExplorerWindow_TextBlock_Text_RecommendedUpdates {
            get {
                return ResourceManager.GetString("NuGetExplorer_ExplorerWindow_TextBlock_Text_RecommendedUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Updates.
        /// </summary>
        internal static string NuGetExplorer_PackageBatchWindow_TextBlock_Text_AvailableUpdates {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageBatchWindow_TextBlock_Text_AvailableUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors: .
        /// </summary>
        internal static string NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetAlertRecords_Errors {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetAlertRecords_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by:.
        /// </summary>
        internal static string NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_CreatedBy {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Create" +
                        "dBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies: .
        /// </summary>
        internal static string NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Dependencies {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Depend" +
                        "encies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads: .
        /// </summary>
        internal static string NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Downloads {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Downlo" +
                        "ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id: .
        /// </summary>
        internal static string NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Id {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed: .
        /// </summary>
        internal static string NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Installed {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Instal" +
                        "led", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published: .
        /// </summary>
        internal static string NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Published {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Publis" +
                        "hed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        internal static string NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Version {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageDetailsService_PackageToFlowDocument_GetDetailsRecord_Versio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must update the shell in order to apply this update.
        /// </summary>
        internal static string NuGetExplorer_PackageDetailsService_PackageToFlowDocument_Update_The_Shell_Error_Message {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageDetailsService_PackageToFlowDocument_Update_The_Shell_Error_" +
                        "Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No package details found.
        /// </summary>
        internal static string NuGetExplorer_PackageListView_TextBlock_Text_NoPackagesFound {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageListView_TextBlock_Text_NoPackagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerelease.
        /// </summary>
        internal static string NuGetExplorer_PackageListView_TextBlock_Text_Prerelease {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageListView_TextBlock_Text_Prerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available packageDetails sources.
        /// </summary>
        internal static string NuGetExplorer_PackageSourceSettingControl_TextBlock_Text_AvailablePackageSources {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageSourceSettingControl_TextBlock_Text_AvailablePackageSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NuGetExplorer_PackageSourceSettingControl_TextBlock_Text_Name {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageSourceSettingControl_TextBlock_Text_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        internal static string NuGetExplorer_PackageSourceSettingControl_TextBlock_Text_Source {
            get {
                return ResourceManager.GetString("NuGetExplorer_PackageSourceSettingControl_TextBlock_Text_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string NuGetExplorer_PagingView_Button_Content_Back {
            get {
                return ResourceManager.GetString("NuGetExplorer_PagingView_Button_Content_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NuGetExplorer_PagingView_Button_Content_Next {
            get {
                return ResourceManager.GetString("NuGetExplorer_PagingView_Button_Content_Next", resourceCulture);
            }
        }
    }
}
