//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.NuGetExplorer.Example.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.NuGetExplorer.Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet data updated.
        /// </summary>
        internal static string NuGetExplorerExample_ExampleUpgradeListener_Message_Upgraded {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_ExampleUpgradeListener_Message_Upgraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating NuGet data.
        /// </summary>
        internal static string NuGetExplorerExample_ExampleUpgradeListener_Message_Upgrading {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_ExampleUpgradeListener_Message_Upgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.NuGetExplorer example.
        /// </summary>
        internal static string NuGetExplorerExample_MainViewModel_Title {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_MainViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed is invalid or unknown.
        /// </summary>
        internal static string NuGetExplorerExample_MainViewModel_Warning_InvalidOrUnknownFeed {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_MainViewModel_Warning_InvalidOrUnknownFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add package source.
        /// </summary>
        internal static string NuGetExplorerExample_MainWindow_Button_Content_AddPackageSource {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_MainWindow_Button_Content_AddPackageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string NuGetExplorerExample_MainWindow_Button_Content_CheckForUpdates {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_MainWindow_Button_Content_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in update window.
        /// </summary>
        internal static string NuGetExplorerExample_MainWindow_Button_Content_OpenInUpdateWindow {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_MainWindow_Button_Content_OpenInUpdateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string NuGetExplorerExample_MainWindow_Button_Content_Settings {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_MainWindow_Button_Content_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show explorer.
        /// </summary>
        internal static string NuGetExplorerExample_MainWindow_Button_Content_ShowExplorer {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_MainWindow_Button_Content_ShowExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verify feed.
        /// </summary>
        internal static string NuGetExplorerExample_MainWindow_Button_Content_VerifyFeed {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_MainWindow_Button_Content_VerifyFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow prereleases.
        /// </summary>
        internal static string NuGetExplorerExample_MainWindow_CheckBox_Content_AllowPrereleases {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_MainWindow_CheckBox_Content_AllowPrereleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package source feed.
        /// </summary>
        internal static string NuGetExplorerExample_MainWindow_TextBlock_Text_PackageSourceFeed {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_MainWindow_TextBlock_Text_PackageSourceFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package source name.
        /// </summary>
        internal static string NuGetExplorerExample_MainWindow_TextBlock_Text_PackageSourceName {
            get {
                return ResourceManager.GetString("NuGetExplorerExample_MainWindow_TextBlock_Text_PackageSourceName", resourceCulture);
            }
        }
    }
}
