//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("WildGums")]
[assembly: AssemblyVersion("3.1.10")]
[assembly: AssemblyFileVersion("3.1.10")]
[assembly: AssemblyInformationalVersion("3.1.10-beta.1")]
[assembly: AssemblyCopyright("Copyright © WildGums 2014 - 2019")]

